src/Entity/UserProfile.php
<?php

namespace App\Entity;

use DateTime;
use App\Repository\UserProfileRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: UserProfileRepository::class)]
class UserProfile
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $avatar = null;

    #[ORM\Column(length: 500, nullable: true)]
    private ?string $bio = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $websiteUrl = null;

    #[ORM\OneToOne(mappedBy: 'Profile', cascade: ['persist', 'remove'])]
    private ?User $User = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateOfBirth = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $town_city_county = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $country = null;

    public function __construct()
    {
        $this->created = new DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getBio(): ?string
    {
        return $this->bio;
    }

    public function setBio(?string $bio): self
    {
        $this->bio = $bio;

        return $this;
    }

    public function getCreated(): ?\DateTimeInterface
    {
        return $this->created;
    }

    public function setCreated(\DateTimeInterface $created): self
    {
        $this->created = $created;

        return $this;
    }

    public function getWebsiteUrl(): ?string
    {
        return $this->websiteUrl;
    }

    public function setWebsiteUrl(?string $websiteUrl): self
    {
        $this->websiteUrl = $websiteUrl;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(User $User): self
    {
        // set the owning side of the relation if necessary
        if ($User->getProfile() !== $this) {
            $User->setProfile($this);
        }

        $this->User = $User;

        return $this;
    }

    public function getDateOfBirth(): ?\DateTimeInterface
    {
        return $this->dateOfBirth;
    }

    public function setDateOfBirth(\DateTimeInterface $dateOfBirth): self
    {
        $this->dateOfBirth = $dateOfBirth;

        return $this;
    }

    public function getTownCityCounty(): ?string
    {
        return $this->town_city_county;
    }

    public function setTownCityCounty(?string $town_city_county): self
    {
        $this->town_city_county = $town_city_county;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): self
    {
        $this->country = $country;

        return $this;
    }
}

src/Controller/ProfileController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Repository\PostRepository;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ProfileController extends AbstractController
{
    #[Route('/profile/{id}', name: 'app_profile_posts')]
    public function index(
        $id,
        PostRepository $posts,
        UserRepository $users
    ): Response
    {
        $user = $users->findUserWithAll($id);

        return $this->render('profile/profile.html.twig', [
            'pageTitle' => $user->getProfile()->getName(),
            'user' => $user,
            'activeTab' => 'posts',
            'posts' => $posts->findAllByUser($user)
        ]);
    }

    #[Route('/profile/{id}/likes', name: 'app_profile_likes')]
    public function likes(
        User $user,
        UserRepository $users
    ): Response
    {
        return $this->render('profile/likes.html.twig', [
            'pageTitle' => $user->getProfile()->getName(),
            'user' => $user,
            'activeTab' => 'likes',
            'posts' => $users->findLikedPostsByUser($user)
        ]);
    }

    #[Route('/profile/{id}/following', name: 'app_profile_following')]
    public function following(User $user): Response
    {
        return $this->render('profile/following.html.twig', [
            'pageTitle' => $user->getProfile()->getName(),
            'user' => $user,
            'activeTab' => 'following'
        ]);
    }

    #[Route('/profile/{id}/followers', name: 'app_profile_followers')]
    public function followers(User $user): Response
    {
        return $this->render('profile/followers.html.twig', [
            'pageTitle' => $user->getProfile()->getName(),
            'user' => $user,
            'activeTab' => 'followers'
        ]);
    }
}

templates/profile/_profile-base.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ pageTitle }} {% endblock %}

{% block breadcrumbs %}
    → {{ pageTitle }}
{% endblock %}

{% block content %}
    {{ include('profile/_profile-header.html.twig', {activeTab: activeTab})}}
    {% block tabContent %}{% endblock %}
{% endblock %}

templates/profile/_profile-header.html.twig
<header class="p-3 pb-0 border-bottom">
    <div class="d-flex justify-content-between align-items-end mb-3">
        {{ include('shared/_avatar.html.twig', { profile: user.profile, size: 128}) }}
        {% if app.user == user %}
            <a href="{{ path('app_settings_profile') }}" class="btn btn-outline-primary">Profile settings</a>
        {% else %}
            {{ include('follower/_follow_button.html.twig', {userToFollow: user}) }}
        {% endif %}

    </div>
    {{ include('shared/_profile-summary.html.twig', {user: user}) }}
    <div class="d-flex flex-column mb-3">
        {% if user.profile.bio %}
            <p>{{ user.profile.bio }}</p>
        {% endif %}
        <div class="d-flex gap-2 flex-wrap">
            {% if user.profile.websiteUrl %}
                <div>
                    {{include('shared/_icon.html.twig', {name: 'link-45deg', size: 16})}}
                    <a href="{% if 'http' not in user.profile.websiteUrl and 'https' not in user.profile.websiteUrl %}http://{% endif %}{{ user.profile.websiteUrl }}"
                       class="text-primary"
                       target="_blank">{{ user.profile.websiteUrl }}</a>
                </div>
            {% endif %}
            {% if user.profile.townCityCounty or user.profile.country %}
                <div>
                    {{include('shared/_icon.html.twig', {name: 'geo-alt', size: 16})}}
                    {% if user.profile.townCityCounty %}
                        <span>{{ user.profile.townCityCounty }},</span>
                    {% endif %}
                    {% if user.profile.country %}
                        <span>{{ user.profile.country }}</span>
                    {% endif %}
                </div>
            {% endif %}
            <div>
                {{include('shared/_icon.html.twig', {name: 'calendar4-week', size: 16})}}
                <span>{{ user.profile.created|date('Y-m-d') }}</span>
            </div>
        </div>
    </div>
    <ul class="profile__tabs">
        <li class="{{ activeTab == 'posts' ? 'active'}}"><a href="{{ path('app_profile_posts', { id: user.id })}}">Posts ({{user.posts|length}})</a></li>
        <li class="{{ activeTab == 'likes' ? 'active'}}"><a href="{{ path('app_profile_likes', { id: user.id })}}">Likes ({{user.likes|length}})</a></li>
        <li class="{{ activeTab == 'following' ? 'active'}}"><a href="{{ path('app_profile_following', { id: user.id })}}">Following ({{user.follows|length}})</a></li>
        <li class="{{ activeTab == 'followers' ? 'active'}}"><a href="{{ path('app_profile_followers', { id: user.id })}}">Followers ({{user.followers|length}})</a></li>
    </ul>
</header>

templates/profile/_user.html.twig
<div class="border-bottom px-3 py-3 d-flex justify-content-between align-items-center overflow-hidden">
    <a href="{{ path('app_profile_posts', {id: user.id}) }}" class="d-flex align-items-center gap-3">
        <img src="{{ asset(profiles ~ user.profile.avatar) }}" alt="dogs" style="width: 32px;" class="rounded-circle bg-dark p-2">
        <div class="d-flex flex-column">
            <span>{{ user.profile.name }}</span>
            <span class="text-muted d-none d-md-block">{{ user.email }} </span>
        </div>
    </a>
    {{ include('follower/_follow_button.html.twig', {userToFollow: user}) }}
</div>

templates/profile/_users-list.html.twig
<div class="d-flex flex-column px-md-3">
    {% if users is not defined or users|length == 0 %}
        <div class="border-bottom px-3 py-4 text-center">
            <p class="h5">{{ emptyListTitle|default('No users') }}</p>
            <p class="text-muted">{{ emptyListMeesage|default('Come back some other time') }}</p>
        </div>
    {% else %}
        {% for user in users %}
            {{include('profile/_user.html.twig', {user: user})}}
        {% endfor %}
    {% endif %}
</div>

templates/profile/followers.html.twig
{% extends 'profile/_profile-base.html.twig' %}

{% block tabContent %}
    {{ include('profile/_users-list.html.twig', { users: user.followers, emptyListTitle: 'No users to display here'}) }}
{% endblock %}

templates/profile/following.html.twig
{% extends 'profile/_profile-base.html.twig' %}

{% block tabContent %}
    {{ include('profile/_users-list.html.twig', { users: user.follows, emptyListTitle: 'No users to display here'}) }}
{% endblock %}

templates/profile/likes.html.twig
{% extends 'profile/_profile-base.html.twig' %}

{% block tabContent %}
    {{ include('post/_posts-list.html.twig', { posts: user.likes, emptyListTitle: 'No liked posts'}) }}
{% endblock %}

templates/profile/profile.html.twig
{% extends 'profile/_profile-base.html.twig' %}

{% block tabContent %}
    {{ include('post/_posts-list.html.twig', { posts: posts}) }}
{% endblock %}