src/Entity/Post.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\PostRepository;

#[ORM\Entity(repositoryClass: PostRepository::class)]
class Post
{
    public const EDIT = 'POST_EDIT';
    public const VIEW = 'POST_VIEW';

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 500)]
    private ?string $content = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created = null;

    #[ORM\ManyToOne(inversedBy: 'posts')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\OneToMany(mappedBy: 'post', targetEntity: Comment::class, orphanRemoval: true)]
    private Collection $comments;

    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'likes')]
    #[ORM\JoinTable('likes')] // add this here to change the name of the table if not it would be post_user
    private Collection $likedBy;

    public function __construct()
    {
        $this->created = new DateTime();
        $this->comments = new ArrayCollection();
        $this->likedBy = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreated(): ?\DateTimeInterface
    {
        return $this->created;
    }

    public function setCreated(\DateTimeInterface $created): self
    {
        $this->created = $created;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setPost($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getPost() === $this) {
                $comment->setPost(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getLikedBy(): Collection
    {
        return $this->likedBy;
    }

    public function addLike(User $likedBy): self
    {
        if (!$this->likedBy->contains($likedBy)) {
            $this->likedBy->add($likedBy);
        }

        return $this;
    }

    public function removeLike(User $likedBy): self
    {
        $this->likedBy->removeElement($likedBy);

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\OneToOne(inversedBy: 'User', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?UserProfile $Profile = null;

    #[ORM\ManyToMany(targetEntity: self::class, inversedBy: 'followers')]
    #[ORM\JoinTable('followers')] // add this here to change the name of the table if not it would be User_user
    private Collection $follows;

    #[ORM\ManyToMany(targetEntity: self::class, mappedBy: 'follows')]
    private Collection $followers;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Post::class, orphanRemoval: true)]
    private Collection $posts;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Comment::class, orphanRemoval: true)]
    private Collection $comments;

    #[ORM\ManyToMany(targetEntity: Post::class, mappedBy: 'likedBy')]
    private Collection $likes;

    public function __construct()
    {
        $this->follows = new ArrayCollection();
        $this->followers = new ArrayCollection();
        $this->posts = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->likes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getProfile(): ?UserProfile
    {
        return $this->Profile;
    }

    public function setProfile(UserProfile $Profile): self
    {
        $this->Profile = $Profile;

        return $this;
    }

    /**
     * @return Collection<int, self>
     */
    public function getFollows(): Collection
    {
        return $this->follows;
    }

    public function follow(self $follow): self
    {
        if (!$this->follows->contains($follow)) {
            $this->follows->add($follow);
        }

        return $this;
    }

    public function unFollow(self $follow): self
    {
        $this->follows->removeElement($follow);

        return $this;
    }

    /**
     * @return Collection<int, self>
     */
    public function getFollowers(): Collection
    {
        return $this->followers;
    }

    public function addFollower(self $follower): self
    {
        if (!$this->followers->contains($follower)) {
            $this->followers->add($follower);
            $follower->follow($this);
        }

        return $this;
    }

    public function removeFollower(self $follower): self
    {
        if ($this->followers->removeElement($follower)) {
            $follower->unFollow($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Post>
     */
    public function getPosts(): Collection
    {
        return $this->posts;
    }

    public function addPost(Post $post): self
    {
        if (!$this->posts->contains($post)) {
            $this->posts->add($post);
            $post->setUser($this);
        }

        return $this;
    }

    public function removePost(Post $post): self
    {
        if ($this->posts->removeElement($post)) {
            // set the owning side to null (unless already changed)
            if ($post->getUser() === $this) {
                $post->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Post>
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(Post $like): self
    {
        if (!$this->likes->contains($like)) {
            $this->likes->add($like);
            $like->addLike($this);
        }

        return $this;
    }

    public function removeLike(Post $like): self
    {
        if ($this->likes->removeElement($like)) {
            $like->removeLike($this);
        }

        return $this;
    }
}

src/Controller/PostController.php
<?php

namespace App\Controller;

use App\Entity\Post;
use App\Entity\Comment;
use App\Form\MainInputType;
use App\Repository\PostRepository;
use App\Repository\CommentRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class PostController extends AbstractController
{
    #[Route('/')]
    public function index(): Response
    {
        return $this->redirectToRoute('app_posts');
    }

    #[Route('/posts/{openPostInput?}', name: 'app_posts', defaults: ['openPostInput' => false])]
    public function posts($openPostInput, PostRepository $posts, Request $request): Response
    {
        $form = $this->createForm(MainInputType::class);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $post = new Post();
            $post->setUser($this->getUser());
            $post->setContent($form->getData('post')['post']);
            $posts->save($post, true);

            $this->addFlash('success', 'Your post has been added');
            return $this->redirectToRoute('app_posts');
        }

        return $this->render('post/posts.html.twig', [
            'pageTitle' => 'Home',
            'posts' => $posts->findAllDsc(),
            'openPostInput' => $openPostInput,
            'mainInputForm' => $form
        ]);
    }

    #[Route('/favourites', name: 'app_post_favourites')]
    public function favourites(PostRepository $posts)
    {
        return $this->render('post/favourites.html.twig', [
            'pageTitle' => 'Favourites',
            'favouritePosts' => $posts->findAllWithMinLikes(2)
        ]);
    }

    #[Route('/post/{id}', name: 'app_post_show')]
    public function show(Post $post): Response
    {
        return $this->render('post/post.html.twig', [
            'pageTitle' => 'Post',
            'post' => $post
        ]);
    }

    #[Route('/post/{id}/edit', name: 'app_post_edit')]
    public function edit(Post $post, PostRepository $posts, Request $request): Response
    {
        $form = $this->createForm(MainInputType::class);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $post->setContent($form->getData('post')['post']);
            $posts->save($post, true);

            $this->addFlash('success', 'Your post has been edited');
            return $this->redirectToRoute('app_posts');
        }

        $form->get('post')->setData($post->getContent());
        return $this->render('post/edit.html.twig', [
            'pageTitle' => 'Edit',
            'post' => $post,
            'editPost' => true,
            'mainInputForm' => $form
        ]);
    }

    #[Route('/post/{id}/comment', name: 'app_post_comment')]
    #[IsGranted('IS_AUTHENTICATED_FULLY')]
    public function comment(Post $post, CommentRepository $comments, Request $request): Response
    {
        $form = $this->createForm(MainInputType::class);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $comment = new Comment();
            $comment->setUser($this->getUser());
            $comment->setPost($post);
            $comment->setContent($form->getData('post')['post']);
            $comments->save($comment, true);

            $this->addFlash('success', 'Your comment has been added');
            return $this->redirectToRoute('app_post_show', ['id' => $post->getId()]);
        }

        return $this->render('post/comment.html.twig', [
            'pageTitle' => 'Comment',
            'post' => $post,
            'comment' => true,
            'mainInputForm' => $form
        ]);
    }
}

templates/post/_comment.html.twig
<div class="border-bottom px-3 py-4 w-100">
    {{ include('post/_post-header.html.twig', {post: comment}) }}
    <div class="pt-3">
        {{ comment.content }}
    </div>
</div>

templates/post/_comments.html.twig
{% for comment in comments %}
    {{include('post/_comment.html.twig', {comment: comment})}}
{% endfor %}

templates/post/_post-header.html.twig
<header class="post__header d-flex align-items-end gap-2 flex-wrap lh-sm">
    <a href="{{ path('app_profile_posts', {id: post.user.id}) }}" class="post__profile-link d-flex align-items-end gap-2">
        {# <img src="{{ asset(profiles ~ post.user.profile.avatar) }}" alt="dogs" style="width: 32px;" class="rounded-circle bg-dark p-2"> #}
        {{ include('shared/_avatar.html.twig', { profile: post.user.profile, size: 32 }) }}
        <h3 class="post__author h5 m-0">{{ post.user.profile.name }}</h3>
        <span class="post__email text-muted">{{ post.user.email }}</span>
    </a>
    <span class="post__date text-muted">{{ post.created|date('Y-m-d') }}</span>
</header>

templates/post/_post.html.twig
{% set constants = post_constants() %}
<div class="post border-bottom px-3 py-4 d-inline-block w-100 position-relative {{ classes|default('') }}">
    <a href="{{ path('app_post_show', {id: post.id}) }}" class="post-show-link {% if hidePostLink is defined %}d-none{% endif %}"></a>
    {{ include('post/_post-header.html.twig') }}
    <div class="post__content py-3">
        {{ post.content }}
    </div>
    <footer class="post__footer d-flex justify-content-between">
        <a href="{{ path('app_post_comment', {id: post.id}) }}" class="post__icon">
            {{include('shared/_icon.html.twig', {name: 'chat-left', size: 24})}}
            <span class="ms-1">{{ post.comments|length }}</span>
        </a>
        <a href="{{ is_granted(constants.EDIT, post) ? path('app_post_edit', {id: post.id, post: post}) : '#'}}" class="post__icon">
            {{include('shared/_icon.html.twig', {name: 'pencil-square', size: 24})}}
        </a>
        <a href="{{ path(post.likedBy.contains(app.user) ? 'app_unlike' : 'app_like', {id: post.id})}}" class="d-flex post__icon">
            {{include('shared/_icon.html.twig', {name: 'hand-thumbs-up', size: 24})}}
            <span class="ms-1 lh-sm align-self-center">{{ post.likedBy.count }}</span>
        </a>
        <a href="" class="post__icon copy-to-clipboard" data-url="{{ app.request.getSchemeAndHttpHost() ~ path('app_post_show', {id: post.id}) }}">
            {{include('shared/_icon.html.twig', {name: 'share', size: 24})}}
        </a>
    </footer>
</div>

templates/post/_posts-list.html.twig
<div class="post__list d-flex flex-column px-md-3">
    {% if posts is not defined or posts|length == 0%}
        <div class="border-bottom px-3 py-4 text-center">
            <p class="h5">{{ emptyListTitle|default('No posts') }}</p>
            <p class="text-muted">{{ emptyListMeesage|default('Come back some other time') }}</p>
        </div>
    {% else %}
        {% for post in posts %}
            {{include('post/_post.html.twig', {post: post})}}
        {% endfor %}
    {% endif %}
</div>

templates/post/comment.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ pageTitle }} {% endblock %}

{% block breadcrumbs %}
    → <a href="{{ path('app_post_show', {id: post.id}) }}">Post</a> → {{ pageTitle }}
{% endblock %}

{% block content %}
    <div class="px-md-3">
        {{ include('post/_post.html.twig') }}
        {{ include('post/_comments.html.twig', {comments: post.comments}) }}
    </div>
{% endblock %}

templates/post/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ pageTitle }} {% endblock %}

{% block breadcrumbs %}
    → <a href="{{ path('app_post_show', {id: post.id}) }}">Post</a> → {{ pageTitle }}
{% endblock %}

templates/post/favourites.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ pageTitle }} {% endblock %}

{% block content %}
    {{ include('post/_posts-list.html.twig', {posts: favouritePosts}) }}
{% endblock %}

templates/post/post.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ pageTitle }} {% endblock %}

{% block breadcrumbs %}
    → {{ pageTitle }}
{% endblock %}

{% block content %}
    <div class="px-md-3">
        {{ include('post/_post.html.twig', {hidePostLink: true}) }}
        {{ include('post/_comments.html.twig', {comments: post.comments}) }}
    </div>
{% endblock %}

templates/post/posts.html.twig
{% extends 'base.html.twig' %}
{# {{include('shared/_icon.html.twig', {name: 'share-fill'})}} #}

{% block title %} {{ pageTitle }} {% endblock %}

{% block content %}
    {{ include('post/_posts-list.html.twig') }}
{% endblock %}